language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-source --no-interaction
  - npm install selenium-webdriver selenium-chromedriver
  - npm install mocha coffee-script chai chai-as-promised
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable

script:
  - phpunit
  - node_modules/.bin/mocha ./test/js/integration-test.coffee --compilers coffee:coffee-script/register

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

notifications:
    on_success: never
    on_failure: always