language: php

php:
  - 5.3

env:
  - TRAVIS_NODE_VERSION="6"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

before_script:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-fastcgi php5-curl php5-mysql php5-intl
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -i -e "s,/var/www,$(pwd),g" --in-place /etc/apache2/sites-available/default
  #- echo "127.0.0.1 http://site.dev" | sudo tee --append /etc/hosts > /dev/null
  - echo "ServerName localhost" | sudo tee /etc/hosts
  #- echo "ServerName localhost" | sudo tee /etc/apache2/conf-available/servername.conf
  #- sudo a2enconf servername
  - sudo /etc/init.d/apache2 restart
  - npm update
  - bower install jquery bootstrap jquery-ui autobahnjs amplify modelobserver
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - wget http://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.1.jar
  - java -jar selenium-server-standalone-3.0.1.jar > /tmp/selenium.log 2> /tmp/selenium.error &
  - composer install --prefer-source --no-interaction
  - phpenv config-add custom-php.ini
  #- ls -l $(pwd)
  - sleep 5

script:
  - phpunit
  - mocha ./test/js/integration-test.coffee --compilers coffee:coffee-script/register --timeout 30000
  - mocha ./test/js/test.js --timeout 30000

matrix:
  fast_finish: true

notifications:
  on_success: never
  on_failure: always