language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart
  - npm install -g bower
  - bower install jquery bootstrap jquery-ui autobahnjs amplify modelobserver
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar
  - java -jar selenium-server-standalone-2.39.0.jar > /tmp/selenium.log 2> /tmp/selenium.error &
  - composer install --prefer-source --no-interaction

script:
  - phpunit
  - node_modules/.bin/mocha ./test/js/integration-test.coffee --compilers coffee:coffee-script/register  --timeout 30000
  - node_modules/.bin/mocha ./test/js/test.js --timeout 30000

matrix:
  fast_finish: true

notifications:
    on_success: never
    on_failure: always