language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl php5-ssl
  - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart
  - composer self-update
  - composer install --prefer-source --no-interaction
  - npm install selenium-webdriver selenium-chromedriver
  - npm install mocha coffee-script chai chai-as-promised
  - wget http://chromedriver.googlecode.com/files/chromedriver_linux32_23.0.1240.0.zip && unzip chromedriver_linux32_23.0.1240.0.zip && sudo mv chromedriver /usr/bin
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar
  - java -jar selenium-server-standalone-2.31.0.jar > /dev/null &
  - sleep 5

script:
  - phpunit
  - node_modules/.bin/mocha ./test/js/integration-test.coffee --compilers coffee:coffee-script/register

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

notifications:
    on_success: never
    on_failure: always