language: php

php:
  - 5.4

env:
  - TRAVIS_NODE_VERSION="6"

install:
  # new version of node and npm
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

before_script:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5
  - sudo apt-get install -y --force-yes php5-dev php-pear php5-curl php5-mysql php5-intl php5-gd php5-json php5-sqlite php5-pgsql
  - sudo a2enmod headers
  - phpenv config-add custom-php.ini
  #- phpenv config-rm xdebug.ini
  - sudo cp -f travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -i -e "s,/var/www,$(pwd),g" --in-place /etc/apache2/sites-available/default
  - echo "ServerName localhost" | sudo tee /etc/hosts
  - sudo /etc/init.d/apache2 restart
  - npm update
  - bower install jquery bootstrap jquery-ui autobahnjs amplify modelobserver
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - wget http://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.1.jar
  - java -jar selenium-server-standalone-3.0.1.jar > /tmp/selenium.log 2> /tmp/selenium.error &
  - composer install --prefer-source --no-interaction

script:
  - phpunit
  #- mocha ./test/js/integration-test.coffee --compilers coffee:coffee-script/register --timeout 30000
  - mocha ./test/js/totodoo.coffee --compilers coffee:coffee-script/register --timeout 30000
  - mocha ./test/js/test.js --timeout 30000

matrix:
  fast_finish: true

notifications:
  on_success: never
  on_failure: always

deploy:
  provider: heroku
  api_key:
    secure: "P0Jp5qyzvxJ9n67eMd8mwmyN6cihu97OIwpF4DLaM/yf1OPMaVzb72e3wpucUb4ZprlZ/bHa8fnGNYhHLcyFzkrjK8vWh96BnEsoJQYm37ex69CYMjrry1wn1op4rF3r3hLKTZ18/YiBZ06XHx+zmHq4TGQiBFEILEsltulrVpUGELywHDdlj0yHu0Bhw1Lt2g5K8W8i6BisuVgnOHvEe8z2q5dOiKDREvVYxmS6tGNdr4FpIy7FFxBkvH7uFxeF15C/AoHjo0tu6FgYLeGcdwIqKXxdcTqhERomw8jLHaatCkX7VIvE2xaXuvtThx/C3nWuC5g3e+oG9k/+qvi/f2+Si91lzHT1+bOoC58shj6A84pIK1gpXSHbS+VshzxficCmAan9pyWsP75vNTK6sFTdKBwbJ7nae/Zv2JlXv6/SB6VQa6wf7r7fgIseohZQZBHzi1ukLqGVynNybG7wwHjaSBM3BKxZxM2X6+XOZYIbep9G3HrdshtNHj6c2u7lZym85jAqcZKZYvocRs8o+nux6D5/ZTlapRV7zyMEJYKvkiCfe4WTF5qODC6ghKTB2B63tG+TSMXAnQsjRZRsS4+9bRKPGJ5e2KWRZhD+7316z7rRZvljqVGEVk27gxyrHem1YvVz1u79/H6mtlDdZ7SFfKl4HqIr2GrzcfIEVkc="
  app: totodoo
  on:
    repo: markomanninen/totodoo
