language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-source --no-interaction
  - npm install selenium-webdriver selenium-chromedriver
  - npm install mocha coffee-script chai chai-as-promised
  - wget http://chromedriver.googlecode.com/files/chromedriver_linux32_23.0.1240.0.zip && unzip chromedriver_linux32_23.0.1240.0.zip && sudo mv chromedriver /usr/bin

script:
  - phpunit
  - node_modules/.bin/mocha ./test/js/integration-test.coffee --compilers coffee:coffee-script/register

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

notifications:
    on_success: never
    on_failure: always